import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";

import clsx from "clsx";
import Navbar from "@/components/common/navbar/Navbar";
import Sidebar from "@/components/common/sidebar/Sidebar";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-background text-pretty antialiased scroll-smooth")}>
        <Navbar />
        <div className="md:grid md:grid-cols-[1fr,3fr]">
          <div className="w-[320px]">
            <Sidebar />
          </div>
          <div className="p-5 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
